name: alazab-ecosystem

services:
  configurator:
    image: ${FRAPPE_DOCKER_REGISTRY:-ghcr.io/frappe/frappe}/configurator:${FRAPPE_VERSION:-v15.8.3}
    deploy:
      restart_policy:
        condition: none
    entrypoint:
      - bash
      - -c
    command:
      - >
        ls -1 apps > sites/apps.txt;
        bench set-config -g db_host $$DB_HOST;
        bench set-config -g redis_cache "$$REDIS_CACHE";
        bench set-config -g redis_queue "$$REDIS_QUEUE";
        bench set-config -g redis_socketio "$$REDIS_SOCKETIO";
        bench set-config -g mail_server "$$MAIL_SERVER";
        bench set-config -g mail_port "$$MAIL_PORT";
        bench set-config -g use_ssl "$$MAIL_USE_SSL";
        bench set-config -g mail_login "$$MAIL_USERNAME";
        bench set-config -g mail_password "$$MAIL_PASSWORD";
        bench set-config -g auto_email_reports "$$AUTO_EMAIL_REPORTS";
        bench set-config -g developer_mode "$$DEVELOPER_MODE";
        bench set-config -g server_script_enabled true;
        bench set-config -g disable_website_cache true;
        bench set-config -g company_name "$$COMPANY_NAME";
        bench set-config -g company_domain "$$COMPANY_DOMAIN";
        bench set-config -g default_currency "$$DEFAULT_CURRENCY";
        bench set-config -g default_country "$$DEFAULT_COUNTRY";
    environment:
      DB_HOST: ${DB_HOST}
      REDIS_CACHE: ${REDIS_CACHE_URL:-redis://redis:6379/0}
      REDIS_QUEUE: ${REDIS_QUEUE_URL:-redis://redis:6379/1}
      REDIS_SOCKETIO: ${REDIS_SOCKETIO_URL:-redis://redis:6379/2}
      MAIL_SERVER: ${MAIL_SERVER}
      MAIL_PORT: ${MAIL_PORT:-587}
      MAIL_USE_SSL: ${MAIL_USE_SSL:-true}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      AUTO_EMAIL_REPORTS: ${AUTO_EMAIL_REPORTS:-0}
      DEVELOPER_MODE: ${DEVELOPER_MODE:-1}
      COMPANY_NAME: ${COMPANY_NAME:-Alazab Construction & Engineering}
      COMPANY_DOMAIN: ${COMPANY_DOMAIN:-al-azab.co}
      DEFAULT_CURRENCY: ${DEFAULT_CURRENCY:-EGP}
      DEFAULT_COUNTRY: ${DEFAULT_COUNTRY:-Egypt}
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  backend:
    image: ${FRAPPE_DOCKER_REGISTRY:-ghcr.io/frappe/frappe}/frappe:${FRAPPE_VERSION:-v15.8.3}
    deploy:
      replicas: 2
    links:
      - configurator
    depends_on:
      - configurator
      - mariadb
      - redis
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    environment:
      - FRAPPE_SITE_NAME_HEADER=${SITES:-$}

  frontend:
    image: ${FRAPPE_DOCKER_REGISTRY:-ghcr.io/frappe/frappe}/frappe:${FRAPPE_VERSION:-v15.8.3}
    deploy:
      replicas: 1
    command: ["nginx-entrypoint.sh"]
    environment:
      BACKEND: backend:8000
      FRAPPE_SITE_NAME_HEADER: ${SITES:-$}
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: ${UPSTREAM_REAL_IP_ADDRESS:-127.0.0.1}
      UPSTREAM_REAL_IP_HEADER: ${UPSTREAM_REAL_IP_HEADER:-X-Forwarded-For}
      UPSTREAM_REAL_IP_RECURSIVE: ${UPSTREAM_REAL_IP_RECURSIVE:-off}
      PROXY_READ_TIMEOUT: ${PROXY_READ_TIMEOUT:-120}
      CLIENT_MAX_BODY_SIZE: ${CLIENT_MAX_BODY_SIZE:-50m}
    volumes:
      - sites:/usr/share/nginx/html/sites
      - logs:/var/log/nginx
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/alazab-common.conf:/etc/nginx/conf.d/alazab-common.conf:ro
    depends_on:
      - backend
      - websocket
    ports:
      - "8080:8080"
      - "443:443"

  websocket:
    image: ${FRAPPE_DOCKER_REGISTRY:-ghcr.io/frappe/frappe}/frappe:${FRAPPE_VERSION:-v15.8.3}
    deploy:
      replicas: 1
    command: ["node", "/home/frappe/frappe-bench/apps/frappe/socketio.js"]
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    depends_on:
      - redis

  queue-short:
    image: ${FRAPPE_DOCKER_REGISTRY:-ghcr.io/frappe/frappe}/frappe:${FRAPPE_VERSION:-v15.8.3}
    deploy:
      replicas: 1
    command: ["bench", "worker", "--queue", "short,default"]
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    depends_on:
      - redis

  queue-long:
    image: ${FRAPPE_DOCKER_REGISTRY:-ghcr.io/frappe/frappe}/frappe:${FRAPPE_VERSION:-v15.8.3}
    deploy:
      replicas: 1
    command: ["bench", "worker", "--queue", "long,default,short"]
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    depends_on:
      - redis

  scheduler:
    image: ${FRAPPE_DOCKER_REGISTRY:-ghcr.io/frappe/frappe}/frappe:${FRAPPE_VERSION:-v15.8.3}
    deploy:
      replicas: 1
    command: ["bench", "schedule"]
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    deploy:
      replicas: 1
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

  mariadb:
    image: mariadb:10.11
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
      - --innodb-buffer-pool-size=512M
      - --innodb-log-file-size=128M
      - --max-allowed-packet=256M
      - --max-connections=200
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME:-frappe}
      MYSQL_USER: ${DB_USER:-frappe}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./config/mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf
    ports:
      - "3306:3306"

volumes:
  mariadb-data:
  redis-data:
  sites:
  logs:
