name: alazab-ecosystem

services:
  configurator:
    image: frappe/erpnext:${FRAPPE_VERSION:-v15.64.1}
    deploy:
      restart_policy:
        condition: none
    entrypoint:
      - bash
      - -c
    command:
      - >
        ls -1 apps > sites/apps.txt;
        bench set-config -g db_host $$DB_HOST;
        bench set-config -g redis_cache "$$REDIS_CACHE";
        bench set-config -g redis_queue "$$REDIS_QUEUE";
        bench set-config -g redis_socketio "$$REDIS_SOCKETIO";
        bench set-config -g developer_mode "$$DEVELOPER_MODE";
        bench set-config -g server_script_enabled true;
        bench set-config -g disable_website_cache true;
        bench set-config -g company_name "$$COMPANY_NAME";
        bench set-config -g company_domain "$$COMPANY_DOMAIN";
        bench set-config -g default_currency "$$DEFAULT_CURRENCY";
        bench set-config -g default_country "$$DEFAULT_COUNTRY";
    environment:
      DB_HOST: ${DB_HOST}
      REDIS_CACHE: ${REDIS_CACHE_URL}
      REDIS_QUEUE: ${REDIS_QUEUE_URL}
      REDIS_SOCKETIO: ${REDIS_SOCKETIO_URL}
      DEVELOPER_MODE: ${DEVELOPER_MODE:-1}
      COMPANY_NAME: ${COMPANY_NAME}
      COMPANY_DOMAIN: ${COMPANY_DOMAIN}
      DEFAULT_CURRENCY: ${DEFAULT_CURRENCY}
      DEFAULT_COUNTRY: ${DEFAULT_COUNTRY}
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  backend:
    image: frappe/erpnext:${FRAPPE_VERSION:-v15.64.1}
    deploy:
      replicas: 2
    depends_on:
      - configurator
      - mariadb
      - redis
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    environment:
      - FRAPPE_SITE_NAME_HEADER=${SITES}

  frontend:
    image: frappe/erpnext:${FRAPPE_VERSION:-v15.64.1}
    deploy:
      replicas: 1
    command: ["nginx-entrypoint.sh"]
    environment:
      BACKEND: backend:8000
      FRAPPE_SITE_NAME_HEADER: ${SITES}
      SOCKETIO: websocket:9000
      PROXY_READ_TIMEOUT: ${TIMEOUT:-120}
      CLIENT_MAX_BODY_SIZE: 50m
    volumes:
      - sites:/usr/share/nginx/html/sites
      - logs:/var/log/nginx
    depends_on:
      - backend
      - websocket
    ports:
      - "8080:8080"

  websocket:
    image: frappe/erpnext:${FRAPPE_VERSION:-v15.64.1}
    deploy:
      replicas: 1
    command: ["node", "/home/frappe/frappe-bench/apps/frappe/socketio.js"]
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    depends_on:
      - redis

  queue-short:
    image: frappe/erpnext:${FRAPPE_VERSION:-v15.64.1}
    deploy:
      replicas: 1
    command: ["bench", "worker", "--queue", "short,default"]
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    depends_on:
      - redis

  queue-long:
    image: frappe/erpnext:${FRAPPE_VERSION:-v15.64.1}
    deploy:
      replicas: 1
    command: ["bench", "worker", "--queue", "long,default,short"]
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    depends_on:
      - redis

  scheduler:
    image: frappe/erpnext:${FRAPPE_VERSION:-v15.64.1}
    deploy:
      replicas: 1
    command: ["bench", "schedule"]
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    deploy:
      replicas: 1
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

  mariadb:
    image: mariadb:10.11
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
      - --innodb-buffer-pool-size=512M
      - --max-allowed-packet=256M
      - --max-connections=200
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: frappe
      MYSQL_USER: frappe
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mariadb-data:
  redis-data:
  sites:
  logs:
