version: "3.9"

# ███████╗ إعدادات مشتركة بين الخدمات ███████╗
x-customizable-image: &customizable_image
  image: ${DOCKER_IMAGE:-alazab/frappe-ecosystem}:${ERPNEXT_VERSION:-v15.63.0}
  pull_policy: always
  restart: unless-stopped
  networks:
    - alazab-network

x-backend-defaults: &backend_defaults
  <<: *customizable_image
  volumes:
    - alazab-sites:/home/frappe/frappe-bench/sites
    - alazab-assets:/home/frappe/frappe-bench/sites/assets
    - /mnt/erpnext_data/repos:/home/frappe/frappe-bench/apps-custom
  depends_on:
    db:
      condition: service_healthy
    redis-cache:
      condition: service_started

# ███████╗ الخدمات الأساسية ███████╗
services:
  # ┌─────────────────────────────────────────────────┐
  # │ ❶ قاعدة البيانات (MariaDB)                     │
  # └─────────────────────────────────────────────────┘
  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-Root@DBPass456!}
      MYSQL_DATABASE: ${DB_NAME:-frappe}
      MYSQL_USER: ${DB_USER:-frappe}
      MYSQL_PASSWORD: ${DB_PASSWORD:-Frappe@1234}
    volumes:
      - alazab-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - alazab-network

  # ┌─────────────────────────────────────────────────┐
  # │ ❷ خدمة Redis                                   │
  # └─────────────────────────────────────────────────┘
  redis-cache:
    image: redis:6.2-alpine
    command: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - alazab-redis-cache:/data
    networks:
      - alazab-network

  redis-queue:
    image: redis:6.2-alpine
    volumes:
      - alazab-redis-queue:/data
    networks:
      - alazab-network

  # ┌─────────────────────────────────────────────────┐
  # │ ❸ الإعدادات الأولية (Configurator)             │
  # └─────────────────────────────────────────────────┘
  configurator:
    <<: *backend_defaults
    entrypoint: ["bash", "-c"]
    command: >
      echo "$$APPS_JSON_BASE64" | base64 -d > sites/apps.json &&
      bench set-config -g db_host $$DB_HOST &&
      bench set-config -gp db_port $$DB_PORT &&
      bench set-config -g redis_cache "redis://$$REDIS_CACHE" &&
      bench set-config -g redis_queue "redis://$$REDIS_QUEUE" &&
      bench set-config -gp socketio_port $$SOCKETIO_PORT
    environment:
      APPS_JSON_BASE64: ${APPS_JSON_BASE64}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-3306}
      REDIS_CACHE: ${REDIS_CACHE:-redis-cache:6379}
      REDIS_QUEUE: ${REDIS_QUEUE:-redis-queue:6379}
      SOCKETIO_PORT: ${SOCKETIO_PORT:-9000}

  # ┌─────────────────────────────────────────────────┐
  # │ ❹ الخدمة الرئيسية (Backend)                   │
  # └─────────────────────────────────────────────────┘
  backend:
    <<: *backend_defaults
    command: bench start
    depends_on:
      configurator:
        condition: service_completed_successfully

  # ┌─────────────────────────────────────────────────┐
  # │ ❺ واجهة الويب (Frontend)                      │
  # └─────────────────────────────────────────────────┘
  frontend:
    <<: *customizable_image
    ports:
      - "${HTTP_PORT:-8080}:8080"
    command: nginx-entrypoint.sh
    environment:
      BACKEND: backend:8000
      SOCKETIO: websocket:9000
      FRAPPE_SITE_NAME_HEADER: ${SITE_NAME:-alazab.online}
      UPSTREAM_REAL_IP_ADDRESS: ${UPSTREAM_REAL_IP_ADDRESS:-127.0.0.1}
      UPSTREAM_REAL_IP_HEADER: ${UPSTREAM_REAL_IP_HEADER:-X-Forwarded-For}
      PROXY_READ_TIMEOUT: ${PROXY_READ_TIMEOUT:-300s}
      CLIENT_MAX_BODY_SIZE: ${CLIENT_MAX_BODY_SIZE:-100m}
    depends_on:
      - backend
      - websocket

  # ┌─────────────────────────────────────────────────┐
  # │ ❻ WebSocket                                   │
  # └─────────────────────────────────────────────────┘
  websocket:
    <<: *customizable_image
    command: ["node", "/home/frappe/frappe-bench/apps/frappe/socketio.js"]
    depends_on:
      - configurator

  # ┌─────────────────────────────────────────────────┐
  # │ ❼ معالجة المهام في الخلفية                    │
  # └─────────────────────────────────────────────────┘
  worker-short:
    <<: *backend_defaults
    command: bench worker --queue short,default

  worker-long:
    <<: *backend_defaults
    command: bench worker --queue long,default

  scheduler:
    <<: *backend_defaults
    command: bench schedule

  # ┌─────────────────────────────────────────────────┐
  # │ ❽ النسخ الاحتياطي التلقائي                    │
  # └─────────────────────────────────────────────────┘
  backup:
    image: alpine
    volumes:
      - alazab-sites:/source
      - /mnt/erpnext_data/backups:/backup
    command: >
      sh -c "tar czf /backup/backup-$$(date +'%Y%m%d').tar.gz /source &&
      find /backup -name '*.tar.gz' -mtime +7 -delete"
    restart: on-failure
    depends_on:
      - backend

# ███████╗ تعريف الشبكات والمجلدات ███████╗
networks:
  alazab-network:
    driver: bridge
    name: alazab-network

volumes:
  alazab-sites:
  alazab-assets:
  alazab-db:
  alazab-redis-cache:
  alazab-redis-queue:
